import type { HelpTopic } from '@/lib/help/types'

export const managerHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Manager navigation',
    summary: 'Daily ops for one property — no GRA or owner refunds.',
    steps: [
      'Dashboard — occupancy, outstanding remaining due (not revenue), complaints, housekeeping, ops calendar.',
      'Reservations & Guests — full front-desk workflow plus stay discounts.',
      'Billing — issue invoices, record payments, print or WhatsApp bills (refunds stay with the owner).',
      'Housekeeping — kanban board for room cleaning.',
      'Complaints — assign technicians and close work after guest sign-off.',
      'Payroll — prepare draft pay runs; owner approves and marks paid.',
      'Guest portal settings — Wi-Fi copy, requests, and rules — on the dashboard Guest portal tab.',
      'Staff — invite receptionists and technicians.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu'],
  },
  {
    id: 'complaints',
    title: 'Complaint workflow',
    summary: 'Assign, then close after the guest confirms.',
    steps: [
      'Guest or receptionist logs a complaint — you assign a technician.',
      'The technician can start immediately. Invoices are optional cost records, not a start-work lock.',
      'When they mark complete, the guest signs off in the portal (if the issue is linked to a guest).',
      'Then you approve completion and pick the room status — Resolved.',
      'Legacy “invoice pending approval” jobs: tap Release to technician.',
    ],
    href: '/manager/complaints',
    hrefLabel: 'Open complaints',
    keywords: ['complaint', 'assign', 'technician', 'approve', 'sign-off', 'sign off'],
    pathPrefixes: ['/manager/complaints'],
  },
  {
    id: 'housekeeping',
    title: 'Housekeeping board',
    summary: 'Track dirty, cleaning, and ready rooms.',
    steps: [
      'Open Housekeeping — kanban columns by status.',
      'Rooms move to Cleaning automatically after checkout.',
      'Clean done creates an Inspect task; inspect done makes the room Available.',
      'Mobile: /mobile/housekeeping for floor staff.',
    ],
    href: '/manager/housekeeping',
    hrefLabel: 'Open housekeeping',
    keywords: ['housekeeping', 'cleaning', 'kanban', 'room'],
    pathPrefixes: ['/manager/housekeeping'],
  },
  {
    id: 'checkout',
    title: 'Help staff with checkout',
    summary: 'Departure after pay-at-check-in — collect only unpaid extras.',
    steps: [
      'Stay payment is taken at check-in. Begin checkout locks the folio; complete releases the room.',
      'Collect remaining balance only if folio extras left Outstanding.',
      'Watch for Overstay badges — guest past departure time.',
      'Approve late checkout on overstay if the guest needs more time.',
      'Record walkout only if they left without paying.',
    ],
    href: '/manager/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['checkout', 'overstay', 'walkout', 'late checkout'],
    pathPrefixes: ['/manager/reservations'],
  },
  {
    id: 'guest-portal',
    title: 'Guest portal & requests',
    summary: 'What guests see on their phones.',
    steps: [
      'Dashboard → Guest portal tab for Wi-Fi copy, rules, and request settings.',
      'Guests sidebar → QR code, portal links, and PINs for checked-in guests.',
      'Review housekeeping, late checkout, and extension requests on the dashboard.',
    ],
    href: '/manager/dashboard#guest-portal',
    hrefLabel: 'Portal settings',
    keywords: ['guest portal', 'requests', 'wifi', 'qr', 'pin'],
    pathPrefixes: ['/manager/dashboard', '/manager/guests'],
  },
  {
    id: 'guest-links',
    title: 'Guest portal links & QR',
    summary: 'Share access with checked-in guests.',
    steps: [
      'Open Guests in the sidebar.',
      'Generate or copy a personal link, or share the property QR + PIN — only while they are in-house.',
      'Portal access ends at check-out; do not issue a new link to a past guest.',
      'Use WhatsApp or email share buttons from the guest detail panel.',
    ],
    href: '/manager/guests',
    hrefLabel: 'Open guests',
    keywords: ['guest portal', 'qr', 'pin', 'whatsapp', 'link'],
    pathPrefixes: ['/manager/guests'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system with real stay dates.',
    steps: [
      'Guests → Register in-house guest.',
      'Enter real arrival (can be past) and planned departure.',
      'Collect payment on the stay invoice, then share the portal link or PIN.',
      'Do not use Check in now for people already staying.',
    ],
    href: '/manager/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest'],
    pathPrefixes: ['/manager/guests'],
  },
  {
    id: 'billing',
    title: 'Stay invoices and payments',
    summary: 'Stay invoices at check-in or before; collect at the desk (pay before enter).',
    steps: [
      'Open a confirmed booking → Collect payment before check-in (creates/refreshes the stay invoice).',
      'Or check in first — walk-in / check-in now also creates the stay invoice (optional Include Ghana tax on the form) and opens collect.',
      'Already in house without an invoice? Guests → open guest → Generate stay invoice & collect (uses check-in dates).',
      'Apply % or fixed guest discounts before tax when creating/editing a booking or refreshing the invoice. You may post folio discount credits. Reception cannot.',
      'You can issue stay invoices unpaid (balance due) or create ad-hoc bills from Billing. Reception records payment when issuing.',
      'Tax is optional on issue/refresh — check Include Ghana tax when you need VAT & GRA levies (Tax ID GHA-728071939-8).',
      'Guest ID (Ghana Card, passport, or driver’s licence) remains optional on the guest record and is not the invoice Tax ID.',
      'Record full or partial payments at the desk; refunds stay owner-only. WhatsApp or print the PDF.',
      'Checkout reuses that same stay invoice — it will not create a duplicate.',
    ],
    href: '/manager/invoices',
    hrefLabel: 'Open billing',
    keywords: ['invoice', 'billing', 'payment', 'collect', 'discount', 'ghana card', 'tax id', 'whatsapp'],
    pathPrefixes: ['/manager/invoices', '/manager/reservations'],
  },
  {
    id: 'payroll',
    title: 'Prepare payroll drafts',
    summary: 'Managers draft; owners approve and pay.',
    steps: [
      'Open Payroll — review the current period.',
      'Create or regenerate a draft pay run if the owner has set pay profiles.',
      'You cannot change rates, approve, mark paid, or export MoMo/bank files — ask the owner.',
    ],
    href: '/manager/payroll',
    hrefLabel: 'Open payroll',
    keywords: ['payroll', 'salary', 'wages', 'draft', 'commission'],
    pathPrefixes: ['/manager/payroll'],
  },
  {
    id: 'erase-guest',
    title: 'Erase or delete a guest',
    summary: 'Manager/owner only — remove duplicates or clear personal data.',
    steps: [
      'Open Guests → Erase / delete guest (reception cannot do this).',
      'In-house guests included — erasing ends the stay and frees the room.',
      'With history: erase personal data (invoices stay printable).',
      'With no history: permanently delete the orphan row.',
    ],
    href: '/manager/guests',
    hrefLabel: 'Open guests',
    keywords: ['erase', 'delete', 'duplicate', 'privacy', 'redact'],
    pathPrefixes: ['/manager/guests'],
  },
  {
    id: 'night-audit',
    title: 'Night audit',
    summary: 'Close the business day with the owner.',
    steps: [
      'Dashboard → Night audit when the day ends.',
      'Review occupancy, open balances, and unresolved complaints.',
      'Coordinate with owner on anything still open in Billing.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['night audit', 'monthly audit', 'yearly audit', 'close', 'end of day', 'period close'],
    pathPrefixes: ['/manager/dashboard'],
  },
]
