import type { HelpTopic } from '@/lib/help/types'

export const managerHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Manager navigation',
    summary: 'Daily ops for one property — no owner billing screens.',
    steps: [
      'Dashboard — occupancy, outstanding (not revenue), complaints, housekeeping.',
      'Reservations & Guests — full front-desk workflow.',
      'Housekeeping — kanban board for room cleaning.',
      'Complaints — assign technicians and approve work.',
      'Guest portal settings — Wi-Fi copy, requests, and rules — on the dashboard Guest portal tab.',
      'Guest links & QR — share portal access from Guests in the sidebar.',
      'Staff — invite receptionists and technicians.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu'],
  },
  {
    id: 'complaints',
    title: 'Complaint workflow',
    summary: 'From guest report to resolved.',
    steps: [
      'Guest or receptionist logs a complaint.',
      'You assign a technician and approve their invoice when work is done.',
      'Technician completes the job; you approve completion.',
      'Status moves to Resolved when fully closed.',
    ],
    href: '/manager/complaints',
    hrefLabel: 'Open complaints',
    keywords: ['complaint', 'assign', 'technician', 'approve'],
    pathPrefixes: ['/manager/complaints'],
  },
  {
    id: 'housekeeping',
    title: 'Housekeeping board',
    summary: 'Track dirty, cleaning, and ready rooms.',
    steps: [
      'Open Housekeeping — kanban columns by status.',
      'Rooms move to Cleaning automatically after checkout.',
      'Drag cards or update status when housekeeping finishes.',
      'Mobile: /mobile/housekeeping for floor staff.',
    ],
    href: '/manager/housekeeping',
    hrefLabel: 'Open housekeeping',
    keywords: ['housekeeping', 'cleaning', 'kanban', 'room'],
    pathPrefixes: ['/manager/housekeeping'],
  },
  {
    id: 'checkout',
    title: 'Help staff with checkout',
    summary: 'Same two-step flow as reception.',
    steps: [
      'Begin checkout locks the folio; complete checkout settles payment.',
      'Watch for Overstay badges — guest past departure time.',
      'Approve late checkout on overstay if the guest needs more time.',
      'Record walkout only if they left without paying.',
    ],
    href: '/manager/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['checkout', 'overstay', 'walkout', 'late checkout'],
    pathPrefixes: ['/manager/reservations'],
  },
  {
    id: 'guest-portal',
    title: 'Guest portal & requests',
    summary: 'What guests see on their phones.',
    steps: [
      'Dashboard → Guest portal tab for Wi-Fi copy, rules, and request settings.',
      'Guests sidebar → QR code, portal links, and PINs for checked-in guests.',
      'Review housekeeping, late checkout, and extension requests on the dashboard.',
    ],
    href: '/manager/dashboard#guest-portal',
    hrefLabel: 'Portal settings',
    keywords: ['guest portal', 'requests', 'wifi', 'qr', 'pin'],
    pathPrefixes: ['/manager/dashboard', '/manager/guests'],
  },
  {
    id: 'guest-links',
    title: 'Guest portal links & QR',
    summary: 'Share access with checked-in guests.',
    steps: [
      'Open Guests in the sidebar.',
      'Generate or copy a personal link, or share the property QR + PIN.',
      'Use WhatsApp or email share buttons from the guest detail panel.',
    ],
    href: '/manager/guests',
    hrefLabel: 'Open guests',
    keywords: ['guest portal', 'qr', 'pin', 'whatsapp', 'link'],
    pathPrefixes: ['/manager/guests'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system with real stay dates.',
    steps: [
      'Guests → Register in-house guest.',
      'Enter real arrival (can be past) and planned departure.',
      'Share the portal link or PIN — do not use Check in now for people already staying.',
    ],
    href: '/manager/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest'],
    pathPrefixes: ['/manager/guests'],
  },
  {
    id: 'night-audit',
    title: 'Night audit',
    summary: 'Close the business day with the owner.',
    steps: [
      'Dashboard → Night audit when the day ends.',
      'Review occupancy, open balances, and unresolved complaints.',
      'Coordinate with owner on anything still open in Billing.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['night audit', 'monthly audit', 'yearly audit', 'close', 'end of day', 'period close'],
    pathPrefixes: ['/manager/dashboard'],
  },
]
