import type { HelpTopic } from '@/lib/help/types'

export const managerHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Manager navigation',
    summary: 'Daily ops for one property — no owner billing screens.',
    steps: [
      'Dashboard — occupancy, outstanding (not revenue), complaints, housekeeping.',
      'Reservations & Guests — full front-desk workflow.',
      'Housekeeping — kanban board for room cleaning.',
      'Complaints — assign technicians and approve work.',
      'Guest portal tab — Wi-Fi copy, requests, and rules for guests.',
      'Staff — invite receptionists and technicians.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu'],
  },
  {
    id: 'complaints',
    title: 'Complaint workflow',
    summary: 'From guest report to resolved.',
    steps: [
      'Guest or receptionist logs a complaint.',
      'You assign a technician and approve their invoice when work is done.',
      'Technician completes the job; you approve completion.',
      'Status moves to Resolved when fully closed.',
    ],
    href: '/manager/complaints',
    hrefLabel: 'Open complaints',
    keywords: ['complaint', 'assign', 'technician', 'approve'],
    pathPrefixes: ['/manager/complaints'],
  },
  {
    id: 'housekeeping',
    title: 'Housekeeping board',
    summary: 'Track dirty, cleaning, and ready rooms.',
    steps: [
      'Open Housekeeping — kanban columns by status.',
      'Rooms move to Cleaning automatically after checkout.',
      'Drag cards or update status when housekeeping finishes.',
      'Mobile: /mobile/housekeeping for floor staff.',
    ],
    href: '/manager/housekeeping',
    hrefLabel: 'Open housekeeping',
    keywords: ['housekeeping', 'cleaning', 'kanban', 'room'],
    pathPrefixes: ['/manager/housekeeping'],
  },
  {
    id: 'checkout',
    title: 'Help staff with checkout',
    summary: 'Same two-step flow as reception.',
    steps: [
      'Begin checkout locks the folio; complete checkout settles payment.',
      'Watch for Overstay badges — guest past departure time.',
      'Approve late checkout on overstay if the guest needs more time.',
      'Record walkout only if they left without paying.',
    ],
    href: '/manager/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['checkout', 'overstay', 'walkout', 'late checkout'],
    pathPrefixes: ['/manager/reservations'],
  },
  {
    id: 'guest-portal',
    title: 'Guest portal & requests',
    summary: 'What guests see on their phones.',
    steps: [
      'Dashboard → Guest portal section or sidebar link.',
      'Review housekeeping, late checkout, and extension requests.',
      'Update Wi-Fi and welcome text so front desk does not repeat it.',
    ],
    href: '/manager/dashboard#guest-portal',
    hrefLabel: 'Guest portal',
    keywords: ['guest portal', 'requests', 'wifi'],
    pathPrefixes: ['/manager/dashboard'],
  },
  {
    id: 'night-audit',
    title: 'Night audit',
    summary: 'Close the business day with the owner.',
    steps: [
      'Dashboard → Night audit when the day ends.',
      'Review occupancy, open balances, and unresolved complaints.',
      'Coordinate with owner on anything still open in Billing.',
    ],
    href: '/manager/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['night audit', 'close', 'end of day'],
    pathPrefixes: ['/manager/dashboard'],
  },
]
