import type { HelpTopic } from '@/lib/help/types'

export const ownerHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Owner navigation',
    summary: 'Full portfolio view — operations plus finance.',
    steps: [
      'Dashboard — revenue KPIs, occupancy, outstanding balances, night audit.',
      'Reservations & Guests — same lifecycle as staff, plus full payment controls.',
      'Billing — invoices, partial payments, refunds.',
      'GRA Reports & Analytics — tax exports and trends.',
      'Settings — property details, Airbnb channels, lifecycle crons, guest portal, portfolio.',
      'Use the sidebar property switcher to change active hotel.',
    ],
    href: '/owner/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu', 'portfolio'],
  },
  {
    id: 'outstanding',
    title: 'Outstanding balances',
    summary: 'Find who still owes money.',
    steps: [
      'Check the Outstanding KPI on the dashboard each morning.',
      'Open Billing for unpaid invoices and partial payments.',
      'Filter Reservations by payment status (Unpaid, Deposit paid, etc.).',
      'Walkouts and unpaid check-in exceptions appear here until collected — normal stays are paid at check-in.',
    ],
    href: '/owner/billing',
    hrefLabel: 'Open billing',
    keywords: ['outstanding', 'balance', 'debt', 'unpaid', 'collect'],
    pathPrefixes: ['/owner/billing', '/owner/dashboard'],
  },
  {
    id: 'billing',
    title: 'Record payments and refunds',
    summary: 'Cash, MoMo, card — stay invoices are settled at check-in.',
    steps: [
      'Front desk collects at check-in; Billing is for leftovers, walkouts, and refunds.',
      'Open Billing → find the invoice or reservation.',
      'Record partial or full payment, or issue a refund (owner only for refunds).',
      'Download PDF invoices for guests or GRA filing.',
    ],
    href: '/owner/billing',
    hrefLabel: 'Open billing',
    keywords: ['payment', 'refund', 'invoice', 'momo', 'cash'],
    pathPrefixes: ['/owner/billing'],
  },
  {
    id: 'erase-guest',
    title: 'Erase or delete a guest',
    summary: 'Owner/manager only — privacy erase; hard-delete only orphans.',
    steps: [
      'Open Guests → Erase / delete guest (reception cannot do this).',
      'Works for in-house guests too — that ends the stay and frees the room.',
      'Erase personal data when they have history — invoices and stays remain for compliance.',
      'Permanently delete only when there is no reservation/invoice/complaint history.',
    ],
    href: '/owner/guests',
    hrefLabel: 'Open guests',
    keywords: ['erase', 'delete', 'privacy', 'redact', 'gdpr', 'dpa'],
    pathPrefixes: ['/owner/guests'],
  },
  {
    id: 'payroll',
    title: 'Run staff payroll',
    summary: 'Pay profiles, commissions from cleans, and payouts.',
    steps: [
      'Staff → Set pay on each team member (base pay, MoMo/bank, TIN/SSNIT).',
      'Payroll → add a housekeeping commission rule if cleaners earn per job.',
      'Run payroll for the period, review lines, approve, then mark paid.',
      'Export payslips or the MoMo/bank checklist CSV for disbursement.',
    ],
    href: '/owner/payroll',
    hrefLabel: 'Open payroll',
    keywords: ['payroll', 'salary', 'commission', 'payslip', 'wages', 'ssnit'],
    pathPrefixes: ['/owner/payroll', '/owner/staff'],
  },
  {
    id: 'lifecycle',
    title: 'Reservation lifecycle settings',
    summary: 'Automated holds, no-show, overstay, and archive.',
    steps: [
      'Settings → Property → Reservation lifecycle.',
      'Enable lifecycle v2 to run cron jobs (hold expiry, no-show, overstay, etc.).',
      'Set no-show charge policy, hold durations, and archive delay.',
      'Staff checkout always uses the state machine; crons are optional automation.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Open settings',
    keywords: ['lifecycle', 'cron', 'no-show', 'overstay', 'hold', 'v2'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'airbnb',
    title: 'Airbnb calendar sync',
    summary: 'Import Airbnb bookings and push MOJO dates back to Airbnb.',
    steps: [
      'Settings → Channels.',
      'Paste each listing’s Airbnb Export calendar URL for the matching room.',
      'Copy the MOJO export URL into Airbnb Import calendar.',
      'Use Sync now after connecting; cron refreshes about every 5 minutes.',
      'Check guests in as usual; Channel prepaid when Airbnb already paid.',
    ],
    href: '/owner/settings#channels',
    hrefLabel: 'Open channels',
    keywords: ['airbnb', 'ical', 'calendar', 'ota', 'channel', 'sync'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'staff',
    title: 'Invite staff',
    summary: 'Managers, receptionists, and technicians.',
    steps: [
      'Staff → invite managers and receptionists by email, technicians by phone.',
      'After creating an invite, send the link on WhatsApp to the new team member.',
      'Managers run daily ops; receptionists handle front desk only.',
      'Technicians see assigned tasks on their phones.',
    ],
    href: '/owner/staff',
    hrefLabel: 'Open staff',
    keywords: ['invite', 'staff', 'team', 'receptionist', 'manager'],
    pathPrefixes: ['/owner/staff'],
  },
  {
    id: 'gra',
    title: 'GRA and tax reports',
    summary: 'Export data for Ghana tax compliance.',
    steps: [
      'Set VAT TIN, invoice prefix, and tax rates in Settings first.',
      'GRA Reports — export period summaries and invoice lists.',
      'Stay invoices (created at check-in) include NHIL, GETFund, VAT, and levies when enabled.',
      'Tourism levy (default 1%) is added outside the NHIL/GETFund/VAT base and appears on GRA exports. COVID levy is no longer charged.',
      'Taxed invoices stamp Bill-to Tax ID GHA-728071939-8; hotel VAT Reg stays separate.',
    ],
    href: '/owner/gra-reports',
    hrefLabel: 'Open GRA reports',
    keywords: ['gra', 'tax', 'vat', 'tin', 'levy', 'tourism', 'ghana card'],
    pathPrefixes: ['/owner/gra-reports'],
  },
  {
    id: 'tax-rates',
    title: 'Edit hotel tax rates',
    summary: 'Per-property NHIL, VAT, e-levy, and tourism levy.',
    steps: [
      'Settings → Property → Tax rates (%).',
      'Change a rate only when your GRA treatment differs from the system defaults.',
      'Tourism levy defaults to 1%. Blank uses that default; set 0 to turn it off — it is not part of the VAT base. COVID levy is removed.',
      'New invoices use the rates you save; older invoices keep their frozen snapshot.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Open settings',
    keywords: ['tax rates', 'tourism', 'nhil', 'getfund', 'elevy', 'covid', 'vat'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'guest-portal',
    title: 'Guest portal settings',
    summary: 'Wi-Fi, welcome message, and local guide.',
    steps: [
      'Settings → Guest portal tab.',
      'Set Wi-Fi, parking, emergency phone, and checkout time shown to guests.',
      'Add local guide items guests see in the portal.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Guest portal settings',
    keywords: ['guest portal', 'wifi', 'welcome', 'local guide'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system with real stay dates.',
    steps: [
      'Guests → Register in-house guest.',
      'Enter real arrival (can be past) and planned departure.',
      'A stay invoice is created automatically — collect payment from Billing or the reservation.',
      'Share the portal link or PIN on WhatsApp — automatic welcome SMS is skipped.',
      'Use Walk-in check-in only for guests arriving now.',
    ],
    href: '/owner/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest', 'migration'],
    pathPrefixes: ['/owner/guests'],
  },
]
