import type { HelpTopic } from '@/lib/help/types'

export const ownerHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Owner navigation',
    summary: 'Full portfolio view — operations plus finance.',
    steps: [
      'Dashboard — revenue KPIs, occupancy, outstanding balances, ops calendar, night audit.',
      'Reservations & Guests — same lifecycle as staff, plus discounts and full payment controls.',
      'Billing — invoices, partial payments, refunds, WhatsApp bills.',
      'Payroll — pay runs, housekeeping commissions, payslips.',
      'GRA Reports & Analytics — tax exports and trends.',
      'Settings — property details, tax rates, Airbnb channels, lifecycle crons, guest portal, portfolio.',
      'Use the sidebar property switcher to change active hotel.',
    ],
    href: '/owner/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu', 'portfolio'],
  },
  {
    id: 'outstanding',
    title: 'Outstanding balances',
    summary: 'Find who still owes money.',
    steps: [
      'Check the Outstanding KPI on the dashboard each morning — it is remaining due on open invoices, same as Billing.',
      'Needs attention lists those unpaid invoices plus today’s arrivals and departures (reception does not see invoice totals).',
      'Open Billing for unpaid invoices and partial payments.',
      'Filter Reservations by payment status (Unpaid, Deposit paid, etc.).',
      'Front desk can collect the full stay invoice before check-in, or at check-in. Walkouts and unpaid exceptions stay visible until collected.',
    ],
    href: '/owner/billing',
    hrefLabel: 'Open billing',
    keywords: ['outstanding', 'balance', 'debt', 'unpaid', 'collect'],
    pathPrefixes: ['/owner/billing', '/owner/dashboard'],
  },
  {
    id: 'billing',
    title: 'Record payments and refunds',
    summary: 'Cash, MoMo, card — stay invoices before or at check-in (pay before enter).',
    steps: [
      'Confirmed booking → Collect payment before check-in, or collect in the check-in dialog after arrival.',
      'Managers and owners can issue unpaid stay invoices or create ad-hoc bills from Billing without full payment.',
      'Open Billing → find leftovers, walkouts, partials, and refunds (refunds owner-only).',
      'Tax is optional on issue — check Include Ghana tax for GRA tax invoices.',
      'Download PDF or WhatsApp invoices for guests or GRA filing.',
    ],
    href: '/owner/billing',
    hrefLabel: 'Open billing',
    keywords: ['payment', 'refund', 'invoice', 'momo', 'cash', 'whatsapp'],
    pathPrefixes: ['/owner/billing'],
  },
  {
    id: 'discounts',
    title: 'Guest stay discounts',
    summary: 'Percent or fixed ₵ off, applied before tax.',
    steps: [
      'On New reservation or Edit booking, choose percent or fixed discount and add a reason.',
      'Discounts apply to the pre-tax room base. Reception cannot enter them — they will ask you or a manager.',
      'You can also post a Discount (credit) on the in-house guest folio.',
      'The amount is frozen on the invoice when it is issued or refreshed.',
    ],
    href: '/owner/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['discount', 'percent', 'promo', 'off', 'credit'],
    pathPrefixes: ['/owner/reservations', '/owner/guests', '/owner/billing'],
  },
  {
    id: 'dispute-hold',
    title: 'Billing dispute hold',
    summary: 'Pause checkout while the guest stays in the room.',
    steps: [
      'On Reservations, open an in-house stay or checkout in progress → Dispute hold, and enter a reason.',
      'The guest stays occupying the room. Folio charges and guest requests stay on this stay.',
      'Release hold (note required) to resume the stay, or begin checkout / record walkout from the hold.',
    ],
    href: '/owner/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['dispute', 'hold', 'billing', 'paused'],
    pathPrefixes: ['/owner/reservations', '/owner/guests'],
  },
  {
    id: 'erase-guest',
    title: 'Erase or delete a guest',
    summary: 'Owner/manager only — privacy erase; hard-delete only orphans.',
    steps: [
      'Open Guests → Erase / delete guest (reception cannot do this).',
      'Works for in-house guests too — that ends the stay and frees the room.',
      'Erase personal data when they have history — invoices and stays remain for compliance.',
      'Permanently delete only when there is no reservation/invoice/complaint history.',
    ],
    href: '/owner/guests',
    hrefLabel: 'Open guests',
    keywords: ['erase', 'delete', 'privacy', 'redact', 'gdpr', 'dpa'],
    pathPrefixes: ['/owner/guests'],
  },
  {
    id: 'payroll',
    title: 'Run staff payroll',
    summary: 'Pay profiles, commissions from cleans, and payouts.',
    steps: [
      'Staff → Set pay on each team member (base pay, MoMo/bank, TIN/SSNIT).',
      'Payroll → add a housekeeping commission rule if cleaners earn per job.',
      'Run payroll for the period, review lines, approve, then mark paid.',
      'Export payslips or the MoMo/bank checklist CSV for disbursement.',
    ],
    href: '/owner/payroll',
    hrefLabel: 'Open payroll',
    keywords: ['payroll', 'salary', 'commission', 'payslip', 'wages', 'ssnit'],
    pathPrefixes: ['/owner/payroll', '/owner/staff'],
  },
  {
    id: 'lifecycle',
    title: 'Reservation lifecycle settings',
    summary: 'Automated holds, no-show, overstay, and archive.',
    steps: [
      'Settings → Property → Reservation lifecycle.',
      'Enable lifecycle v2 to run cron jobs (hold expiry, no-show, overstay, etc.).',
      'Set check-in payment minimum — percent (default 50%), fixed ₵, first night, or none. Reception must collect at least this before the guest enters; you and managers can waive.',
      'Set no-show charge policy, hold durations, and archive delay.',
      'Staff checkout always uses the state machine; crons are optional automation.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Open settings',
    keywords: ['lifecycle', 'cron', 'no-show', 'overstay', 'hold', 'v2', 'check-in', 'minimum', 'partial'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'airbnb',
    title: 'Airbnb calendar sync',
    summary: 'Import Airbnb bookings and push MOJO dates back to Airbnb.',
    steps: [
      'Settings → Channels.',
      'Paste each listing’s Airbnb Export calendar URL for the matching room.',
      'Copy the MOJO export URL into Airbnb Import calendar.',
      'Use Sync now after connecting; cron refreshes about every 5 minutes.',
      'Check guests in as usual; Channel prepaid when Airbnb already paid.',
    ],
    href: '/owner/settings#channels',
    hrefLabel: 'Open channels',
    keywords: ['airbnb', 'ical', 'calendar', 'ota', 'channel', 'sync'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'staff',
    title: 'Invite staff',
    summary: 'Managers, receptionists, and technicians.',
    steps: [
      'Staff → invite managers and receptionists by email, technicians by phone.',
      'After creating an invite, send the link on WhatsApp to the new team member.',
      'Managers run daily ops and can record payments; receptionists handle front desk and must collect when issuing stay invoices.',
      'Technicians see assigned tasks on their phones.',
    ],
    href: '/owner/staff',
    hrefLabel: 'Open staff',
    keywords: ['invite', 'staff', 'team', 'receptionist', 'manager'],
    pathPrefixes: ['/owner/staff'],
  },
  {
    id: 'gra',
    title: 'GRA and tax reports',
    summary: 'Export data for Ghana tax compliance.',
    steps: [
      'Set VAT TIN, invoice prefix, and tax rates in Settings first.',
      'GRA Reports — export period summaries and invoice lists.',
      'Stay invoices include NHIL, GETFund, VAT, and levies when Include Ghana tax is checked.',
      'NHIL, GETFund, VAT, and tourism levy are each calculated on the stay amount. VAT is not charged on the levies. Older invoices keep stacked VAT if they were issued that way.',
      'Taxed invoices stamp Bill-to Tax ID GHA-728071939-8; hotel VAT Reg stays separate.',
    ],
    href: '/owner/gra-reports',
    hrefLabel: 'Open GRA reports',
    keywords: ['gra', 'tax', 'vat', 'tin', 'levy', 'tourism', 'ghana card'],
    pathPrefixes: ['/owner/gra-reports'],
  },
  {
    id: 'tax-rates',
    title: 'Edit hotel tax rates',
    summary: 'Per-property NHIL, VAT, e-levy, and tourism levy.',
    steps: [
      'Settings → Property → Tax rates (%).',
      'Change a rate only when your GRA treatment differs from the system defaults.',
      'Tourism levy defaults to 1%. Blank uses that default; set 0 to turn it off. COVID levy is removed.',
      'New invoices use the rates you save; older invoices keep their frozen snapshot.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Open settings',
    keywords: ['tax rates', 'tourism', 'nhil', 'getfund', 'elevy', 'covid', 'vat'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'guest-portal',
    title: 'Guest portal settings',
    summary: 'Wi-Fi, welcome message, and local guide.',
    steps: [
      'Settings → Guest portal tab.',
      'Set Wi-Fi, parking, emergency phone, and checkout time shown to guests.',
      'Add local guide items guests see in the portal.',
    ],
    href: '/owner/settings',
    hrefLabel: 'Guest portal settings',
    keywords: ['guest portal', 'wifi', 'welcome', 'local guide'],
    pathPrefixes: ['/owner/settings'],
  },
  {
    id: 'guest-requests',
    title: 'Guest requests',
    summary: 'Housekeeping, late checkout, and stay extensions from the portal.',
    steps: [
      'Dashboard → Requests tab (not Settings).',
      'Open a request to acknowledge, complete, or decline.',
      'Stay extensions jump to Reservations to pick the new check-out date.',
      'Housekeeping requests can schedule a cleaning task.',
    ],
    href: '/owner/dashboard#guest-requests',
    hrefLabel: 'Open guest requests',
    keywords: ['guest requests', 'housekeeping', 'late checkout', 'extension'],
    pathPrefixes: ['/owner/dashboard'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system with real stay dates.',
    steps: [
      'Guests → Register in-house guest.',
      'Enter real arrival (can be past) and planned departure. Optional ID: Ghana Card, passport, or driver’s licence.',
      'A stay invoice is created automatically — collect payment from Billing or the reservation.',
      'Share the portal link or PIN on WhatsApp — automatic welcome SMS is skipped.',
      'Use Walk-in check-in only for guests arriving now.',
    ],
    href: '/owner/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest', 'migration', 'ghana card', 'passport', 'licence'],
    pathPrefixes: ['/owner/guests'],
  },
]
