import type { HelpTopic } from '@/lib/help/types'

export const receptionistHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Find your way around',
    summary: 'Main screens and what each one is for.',
    steps: [
      'Dashboard — today’s arrivals, departures, and the Requests tab for guest portal requests.',
      'Reservations — bookings, check-in, checkout, deposits, stay invoices.',
      'Billing — view invoices, record payments, print or WhatsApp bills.',
      'Guests — register in-house guests, walk-ins, portal links (in-house only), folio.',
      'Rooms — view nightly/weekly/monthly rates (read-only) and update status.',
      'Access — guest unlock and cards only.',
      'Complaints — log issues on behalf of a guest.',
      'Inventory is manager/owner only — ask them if supplies are low.',
      'Press ⌘K (or use Search) to jump to a page or find a guest quickly.',
    ],
    href: '/receptionist/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu', 'search', 'keyboard', 'inventory', 'stock'],
  },
  {
    id: 'dashboard',
    title: 'Needs attention',
    summary: 'Today’s arrivals and departures — not unpaid invoice totals.',
    steps: [
      'Needs attention at the top of the dashboard lists today’s arrivals and departures.',
      'Unpaid invoice totals stay on owner and manager dashboards.',
      'To collect, open the reservation (Outstanding) or Billing.',
    ],
    href: '/receptionist/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['needs attention', 'dashboard', 'arrivals', 'departures', 'invoice', 'outstanding'],
    pathPrefixes: ['/receptionist/dashboard'],
  },
  {
    id: 'check-in',
    title: 'Check in a guest',
    summary: 'Turn a confirmed booking into an in-house stay and generate the stay invoice.',
    steps: [
      'Open Reservations and find a Confirmed or Pre-arrival booking.',
      'Tap Check in guest — phone number is required.',
      'Optional: enter Ghana Card, passport, or driver’s licence for guest records (invoice Tax ID is always GHA-728071939-8 when taxed).',
      'A stay invoice is created automatically (pay before enter) — collect payment in the dialog. You cannot leave it unpaid.',
      'If the bill is not in the guest’s name, untick Bill to person same as guest and enter the bill-to name.',
      'Share the portal link or QR so the guest can message you or log complaints.',
      'Confirm the room shows Occupied on the Rooms page.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['arrival', 'check in', 'check-in', 'portal', 'qr', 'ghana card', 'passport', 'licence', 'tax id'],
    pathPrefixes: ['/receptionist/reservations', '/receptionist/guests'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system without a fake same-day check-in.',
    steps: [
      'Open Guests → Register in-house guest.',
      'Enter their real arrival date (can be in the past) and planned departure.',
      'Optional: Ghana Card, passport, or driver’s licence for guest records.',
      'Assign their room and rate — a stay invoice is created automatically (Tax ID GHA-728071939-8 when taxed).',
      'Share the portal link or PIN on WhatsApp and collect payment.',
      'Use Walk-in check-in only for guests who are arriving now.',
    ],
    href: '/receptionist/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest', 'migration', 'ghana card', 'passport', 'licence'],
    pathPrefixes: ['/receptionist/guests'],
  },
  {
    id: 'checkout',
    title: 'Check out a guest',
    summary: 'Two-step departure: begin (lock folio) then complete — payment was at check-in.',
    steps: [
      'Payment for the stay is taken at check-in. Checkout only handles departure and any unpaid extras.',
      'Open the Checked in reservation and review Outstanding in the Payment box.',
      'Tap Begin checkout — folio locks so no new charges can be posted.',
      'If Outstanding is ₵0, confirm checkout to release the room.',
      'If there is a remaining balance (folio extras), collect it now — unpaid complete-checkout is blocked.',
      'Checkout refreshes the same stay invoice (no duplicate). Room moves to Cleaning.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['checkout', 'check out', 'payment', 'folio', 'departure'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'dispute-hold',
    title: 'Billing dispute hold',
    summary: 'Checkout is paused; the guest stays in the room.',
    steps: [
      'You cannot start or end a dispute hold.',
      'The guest stays in-house. You can still post folio charges and handle requests.',
      'Ask a manager or owner on Reservations to release the hold or finish checkout.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['dispute', 'hold', 'billing hold', 'paused'],
    pathPrefixes: ['/receptionist/reservations', '/receptionist/guests'],
  },
  {
    id: 'billing',
    title: 'Issue invoices and record payments',
    summary: 'Stay invoices are created at check-in; collect payment before the guest enters.',
    steps: [
      'Check-in creates the stay invoice automatically — choose Include Ghana tax on the check-in form if needed, then record full or partial payment in the collect dialog.',
      'The hotel sets a check-in minimum (Settings → Reservation lifecycle). Collect at least that amount before the guest enters unless a manager waives it.',
      'Bill to can differ from the guest name when you issue or check in.',
      'Billing has no revenue tiles — open the invoice and record payment, print, or WhatsApp.',
      'Or collect before check-in: open a confirmed booking → Collect payment before check-in.',
      'For guests already in house without an invoice: Guests → open guest → Generate stay invoice & collect (uses their check-in dates).',
      'Use Issue invoice & collect on the reservation or Billing if anything remains unpaid mid-stay — reception marks the stay paid when issuing.',
      'Ask a manager or owner if the guest needs a discount, an unpaid invoice document, or an ad-hoc (non-stay) bill.',
      'Tax is optional — check “Include Ghana tax” when you need a GRA tax invoice.',
      'Choose payment method; payment is recorded when you issue from reception. Print or WhatsApp the bill.',
      'Refunds stay owner-only.',
    ],
    href: '/receptionist/billing',
    hrefLabel: 'Open billing',
    keywords: ['invoice', 'billing', 'payment', 'collect', 'receipt', 'discount', 'whatsapp', 'bill to'],
    pathPrefixes: ['/receptionist/billing', '/receptionist/reservations'],
  },
  {
    id: 'walkout',
    title: 'Record a walkout',
    summary: 'Only unpaid-departure exception — guest left without paying.',
    steps: [
      'Use when the guest has already left and did not settle (not for normal pay-later).',
      'Open the in-house reservation → Record walkout → confirm.',
      'The stay invoice keeps balance due; the room is released to Cleaning.',
      'Do not use walkout if the guest is still at the desk — collect remaining and check out.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['walkout', 'walk out', 'unpaid', 'left', 'balance'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'no-show',
    title: 'Mark a no-show',
    summary: 'Guest did not arrive on their check-in date.',
    steps: [
      'Only for Confirmed or Pre-arrival bookings — not checked-in guests.',
      'If a deposit was collected, choose forfeit (you can) or refund (owner only).',
      'Tap Mark no-show on the reservation.',
      'If the guest is in-house, use Check out instead — never cancel or no-show.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['no show', 'no-show', 'noshow', 'arrival', 'absent'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'folio',
    title: 'Post folio charges',
    summary: 'Add minibar, laundry, or other extras during the stay.',
    steps: [
      'Go to Guests and open the in-house guest.',
      'Post to folio — description and amount in ₵.',
      'You cannot post discount credits — ask a manager.',
      'Charges roll into the stay invoice when you refresh it or complete checkout.',
      'You cannot post folio charges while checkout is in progress (folio locked). You can still post during a dispute hold.',
    ],
    href: '/receptionist/guests',
    hrefLabel: 'Open guests',
    keywords: ['folio', 'minibar', 'charge', 'incidental', 'laundry'],
    pathPrefixes: ['/receptionist/guests'],
  },
  {
    id: 'deposit',
    title: 'Record a payment',
    summary: 'Collect part of the stay before check-in or against the stay invoice.',
    steps: [
      'Open the reservation → Payment section → Record payment.',
      'Enter amount (cannot exceed balance due) and payment method.',
      'At check-in, the collect dialog shows the hotel minimum (e.g. 50%) — pay that amount or the full balance.',
      'Managers can waive the minimum for prepaid channels or approved exceptions.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['deposit', 'partial', 'payment', 'momo', 'cash'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'complaints',
    title: 'Log a complaint for a guest',
    summary: 'Create a maintenance issue when the guest reports it at the desk.',
    steps: [
      'Open Complaints → log on behalf of the guest.',
      'Pick category and describe the issue.',
      'Managers assign technicians — the technician can start immediately. You do not assign or close jobs.',
    ],
    href: '/receptionist/complaints',
    hrefLabel: 'Open complaints',
    keywords: ['complaint', 'maintenance', 'issue', 'repair'],
    pathPrefixes: ['/receptionist/complaints'],
  },
]
