import type { HelpTopic } from '@/lib/help/types'

export const receptionistHelpTopics: HelpTopic[] = [
  {
    id: 'nav',
    title: 'Find your way around',
    summary: 'Main screens and what each one is for.',
    steps: [
      'Dashboard — today’s arrivals, requests, and alerts.',
      'Reservations — bookings, check-in, checkout, deposits, stay invoices.',
      'Billing — view invoices, record payments, print or WhatsApp bills.',
      'Guests — register in-house guests, walk-ins, portal links, folio, erase duplicates.',
      'Rooms — view nightly/weekly/monthly rates (read-only) and update status.',
      'Complaints — log issues on behalf of a guest.',
      'Press ⌘K (or use Search) to jump to a page or find a guest quickly.',
    ],
    href: '/receptionist/dashboard',
    hrefLabel: 'Open dashboard',
    keywords: ['navigation', 'menu', 'search', 'keyboard'],
  },
  {
    id: 'check-in',
    title: 'Check in a guest',
    summary: 'Turn a confirmed booking into an in-house stay.',
    steps: [
      'Open Reservations and find a Confirmed or Pre-arrival booking.',
      'Tap Check in guest — phone number is required.',
      'Optional: enter Ghana Card (GHA-#########-#) — it appears as Tax ID on the invoice.',
      'Share the portal link or QR so the guest can message you or log complaints.',
      'Confirm the room shows Occupied on the Rooms page.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['arrival', 'check in', 'check-in', 'portal', 'qr', 'ghana card', 'tax id'],
    pathPrefixes: ['/receptionist/reservations', '/receptionist/guests'],
  },
  {
    id: 'register-in-house',
    title: 'Register guests already in house',
    summary: 'Go-live: put current occupants on the system without a fake same-day check-in.',
    steps: [
      'Open Guests → Register in-house guest.',
      'Enter their real arrival date (can be in the past) and planned departure.',
      'Optional: Ghana Card (GHA-#########-#) for invoice Tax ID.',
      'Assign their room and rate, then share the portal link or PIN on WhatsApp.',
      'Use Walk-in check-in only for guests who are arriving now.',
    ],
    href: '/receptionist/guests',
    hrefLabel: 'Open guests',
    keywords: ['enroll', 'register', 'in house', 'go live', 'existing guest', 'migration', 'ghana card'],
    pathPrefixes: ['/receptionist/guests'],
  },
  {
    id: 'erase-guest',
    title: 'Erase or delete a guest',
    summary: 'Remove wrong or duplicate guest records without destroying invoices.',
    steps: [
      'Open the guest (not in-house) → Erase / delete guest.',
      'If they have stay or invoice history: Erase personal data — name becomes “Redacted guest”; invoices stay printable.',
      'If they have no history (duplicate): Permanently delete removes the row.',
      'In-house guests cannot be erased until checkout is complete.',
    ],
    href: '/receptionist/guests',
    hrefLabel: 'Open guests',
    keywords: ['erase', 'delete', 'remove', 'duplicate', 'redact', 'privacy', 'gdpr'],
    pathPrefixes: ['/receptionist/guests'],
  },
  {
    id: 'checkout',
    title: 'Check out a guest',
    summary: 'Two-step checkout: begin (lock folio) then complete payment.',
    steps: [
      'Open the Checked in reservation and review Outstanding in the Payment box.',
      'Tap Begin checkout — folio locks so no new charges can be posted.',
      'Tap Complete checkout, choose payment method, and confirm.',
      'Check the box when the guest pays the full balance at checkout — any deposit is applied and the remainder is recorded.',
      'Leave it unchecked to check out with balance due — collect later in Billing.',
      'If you already issued an invoice during the stay, checkout refreshes that same invoice (no duplicate).',
      'Room moves to Cleaning automatically.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['checkout', 'check out', 'payment', 'folio', 'departure'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'billing',
    title: 'Issue invoices and record payments',
    summary: 'Bill in-house stays before checkout and collect at the desk.',
    steps: [
      'Open an in-house reservation → Issue invoice & collect.',
      'Optional: apply a % or fixed discount (before tax) with a reason.',
      'Choose payment method; check “paid full balance” when the guest settles now.',
      'Or open Billing to find open invoices and record full or partial payments.',
      'Refunds and ad-hoc (non-stay) invoices are owner-only.',
    ],
    href: '/receptionist/billing',
    hrefLabel: 'Open billing',
    keywords: ['invoice', 'billing', 'payment', 'collect', 'receipt', 'discount'],
    pathPrefixes: ['/receptionist/billing', '/receptionist/reservations'],
  },
  {
    id: 'walkout',
    title: 'Record a walkout',
    summary: 'Guest left without paying at the desk.',
    steps: [
      'Use when the guest has already left and did not settle at reception.',
      'Open the in-house reservation → Record walkout → confirm.',
      'An invoice is created with balance due; the room is released to Cleaning.',
      'Do not use walkout if the guest is still at the desk — use normal checkout instead.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['walkout', 'walk out', 'unpaid', 'left', 'balance'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'no-show',
    title: 'Mark a no-show',
    summary: 'Guest did not arrive on their check-in date.',
    steps: [
      'Only for Confirmed or Pre-arrival bookings — not checked-in guests.',
      'If a deposit was collected, choose forfeit (you can) or refund (owner only).',
      'Tap Mark no-show on the reservation.',
      'If the guest is in-house, use Check out instead — never cancel or no-show.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['no show', 'no-show', 'noshow', 'arrival', 'absent'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'folio',
    title: 'Post folio charges',
    summary: 'Add minibar, laundry, or other extras during the stay.',
    steps: [
      'Go to Guests and open the in-house guest.',
      'Post to folio — description and amount in ₵.',
      'Charges roll into the checkout total automatically.',
      'You cannot post folio charges while checkout is in progress (folio locked).',
    ],
    href: '/receptionist/guests',
    hrefLabel: 'Open guests',
    keywords: ['folio', 'minibar', 'charge', 'incidental', 'laundry'],
    pathPrefixes: ['/receptionist/guests'],
  },
  {
    id: 'deposit',
    title: 'Record a deposit',
    summary: 'Collect part of the stay before or at booking.',
    steps: [
      'Open the reservation → Payment section → Record deposit.',
      'Enter amount (cannot exceed balance due) and payment method.',
      'For Airbnb/Booking.com prepaid stays, use Channel prepaid when applicable.',
    ],
    href: '/receptionist/reservations',
    hrefLabel: 'Open reservations',
    keywords: ['deposit', 'partial', 'payment', 'momo', 'cash'],
    pathPrefixes: ['/receptionist/reservations'],
  },
  {
    id: 'complaints',
    title: 'Log a complaint for a guest',
    summary: 'Create a maintenance issue when the guest reports it at the desk.',
    steps: [
      'Open Complaints → log on behalf of the guest.',
      'Pick category and describe the issue.',
      'Managers assign technicians — you do not approve or assign jobs.',
    ],
    href: '/receptionist/complaints',
    hrefLabel: 'Open complaints',
    keywords: ['complaint', 'maintenance', 'issue', 'repair'],
    pathPrefixes: ['/receptionist/complaints'],
  },
]
