import type { HelpTopic } from '@/lib/help/types'

export const technicianHelpTopics: HelpTopic[] = [
  {
    id: 'tasks',
    title: 'My tasks screen',
    summary: 'Maintenance jobs and housekeeping work.',
    steps: [
      'Tasks shows complaints assigned to you and housekeeping jobs.',
      'Tap a card to open details, message the guest, or update status.',
      'Use ⌘K to search by room number or category.',
      'Bottom bar switches between Tasks and Messages.',
    ],
    href: '/technician/tasks',
    hrefLabel: 'Open tasks',
    keywords: ['tasks', 'jobs', 'home'],
  },
  {
    id: 'complaints',
    title: 'Maintenance complaint flow',
    summary: 'Start as soon as you are assigned — invoices are optional.',
    steps: [
      'Open the job → review category and guest notes.',
      'Tap Start job — you do not wait for invoice approval.',
      'Message the guest from the job if you need access or details. Honour Do Not Disturb.',
      'Optional: submit a materials/labour invoice anytime as a cost record.',
      'Mark complete when finished. The guest signs off in the portal; then the manager closes the job.',
    ],
    href: '/technician/tasks',
    hrefLabel: 'Open tasks',
    keywords: ['complaint', 'repair', 'maintenance', 'invoice', 'start'],
    pathPrefixes: ['/technician/tasks'],
  },
  {
    id: 'housekeeping',
    title: 'Housekeeping tasks',
    summary: 'Room cleaning after checkout.',
    steps: [
      'Claim or accept housekeeping tasks from the pool.',
      'Update status as you clean — managers see progress on the board.',
      'Finishing Clean creates an Inspect task — the room is not Available until Inspect is done.',
      'Checkout automatically creates clean tasks for departed rooms.',
    ],
    href: '/technician/tasks',
    hrefLabel: 'Open tasks',
    keywords: ['housekeeping', 'cleaning', 'room', 'inspect'],
    pathPrefixes: ['/technician/tasks'],
  },
  {
    id: 'messages',
    title: 'Team messages',
    summary: 'Chat with managers — not guest billing.',
    steps: [
      'Messages tab — coordinate with managers on assignments.',
      'Guest chat for a specific repair is inside each complaint job.',
      'Add your phone number so SMS alerts reach you for new jobs.',
    ],
    href: '/technician/messages',
    hrefLabel: 'Open messages',
    keywords: ['messages', 'chat', 'sms', 'phone'],
    pathPrefixes: ['/technician/messages'],
  },
  {
    id: 'phone',
    title: 'Phone and alerts',
    summary: 'Stay reachable for new assignments.',
    steps: [
      'Tap Phone or the banner to add or verify your number.',
      'You receive SMS when managers assign jobs.',
      'Call manager button reaches property managers directly.',
    ],
    href: '/technician/tasks',
    hrefLabel: 'Open tasks',
    keywords: ['phone', 'sms', 'alert', 'contact'],
  },
]
