import { jsPDF } from 'jspdf'
import { formatPeriodLabel } from '@/lib/payroll/calculate'
import type { CommissionEntryRow, PayRunLineRow, PayRunRow } from '@/lib/payroll/types'

const BRAND = {
  purpleInk: [42, 13, 92] as const,
  purple: [91, 24, 199] as const,
  gold: [212, 166, 46] as const,
  muted: [92, 74, 128] as const,
  line: [221, 214, 254] as const,
}

function money(value: number): string {
  return `GHS ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export function downloadPayslipPdf(input: {
  hotelName: string
  run: PayRunRow
  line: PayRunLineRow
  commissions?: CommissionEntryRow[]
}): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const margin = 18
  let y = 22

  doc.setFillColor(...BRAND.purpleInk)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(input.hotelName, margin, 14)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Payslip', margin, 22)

  y = 40
  doc.setTextColor(...BRAND.purpleInk)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(input.line.staffName, margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...BRAND.muted)
  doc.text(
    `${input.line.staffSpecialty || input.line.staffRole} · ${
      input.run.periodStart && input.run.periodEnd
        ? formatPeriodLabel(input.run.periodStart, input.run.periodEnd)
        : 'Pay period'
    }`,
    margin,
    y,
  )

  y += 12
  doc.setDrawColor(...BRAND.line)
  doc.line(margin, y, 210 - margin, y)
  y += 10

  const rows: Array<[string, string]> = [
    ['Base pay', money(input.line.basePay)],
    ['Commission', money(input.line.commission)],
    ['Allowances', money(input.line.allowances)],
    ['Deductions', money(input.line.deductions)],
    ['Net pay', money(input.line.netPay)],
    ['Status', input.line.status],
  ]

  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...BRAND.muted)
    doc.setFontSize(9)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...BRAND.purpleInk)
    doc.setFontSize(10)
    doc.text(value, 210 - margin, y, { align: 'right' })
    y += 8
  }

  if (input.commissions && input.commissions.length > 0) {
    y += 6
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...BRAND.purple)
    doc.text('Commission detail', margin, y)
    y += 8
    for (const c of input.commissions) {
      if (y > 270) {
        doc.addPage()
        y = 22
      }
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(...BRAND.muted)
      doc.text(`${c.accruedOn} · ${c.description}`, margin, y, { maxWidth: 140 })
      doc.setTextColor(...BRAND.purpleInk)
      doc.text(money(c.amount), 210 - margin, y, { align: 'right' })
      y += 6
    }
  }

  y = Math.max(y + 16, 260)
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.muted)
  doc.text('Generated by MoJo PMS · For payroll records', margin, y)

  const safeName = input.line.staffName.replace(/[^\w.-]+/g, '_')
  doc.save(`payslip-${safeName}.pdf`)
}

export function downloadPayRunSummaryPdf(input: {
  hotelName: string
  run: PayRunRow
  lines: PayRunLineRow[]
}): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const margin = 14
  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...BRAND.purpleInk)
  doc.text(`${input.hotelName} — Payroll summary`, margin, y)
  y += 8
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...BRAND.muted)
  const period =
    input.run.periodStart && input.run.periodEnd
      ? formatPeriodLabel(input.run.periodStart, input.run.periodEnd)
      : ''
  doc.text(`Period: ${period} · Status: ${input.run.status}`, margin, y)
  y += 6
  doc.text(
    `Net ${money(input.run.totalNet)} · Commission ${money(input.run.totalCommission)} · ${input.run.employeeCount} staff`,
    margin,
    y,
  )
  y += 12

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.purpleInk)
  const cols = [margin, 58, 88, 118, 148, 178]
  doc.text('Staff', cols[0]!, y)
  doc.text('Base', cols[1]!, y)
  doc.text('Comm.', cols[2]!, y)
  doc.text('Ded.', cols[3]!, y)
  doc.text('Net', cols[4]!, y)
  doc.text('Status', cols[5]!, y)
  y += 5
  doc.setDrawColor(...BRAND.line)
  doc.line(margin, y, 196, y)
  y += 5

  doc.setFont('helvetica', 'normal')
  for (const line of input.lines.filter((l) => l.status !== 'excluded')) {
    if (y > 280) {
      doc.addPage()
      y = 20
    }
    doc.setTextColor(...BRAND.purpleInk)
    doc.text(line.staffName.slice(0, 22), cols[0]!, y)
    doc.text(money(line.basePay).replace('GHS ', ''), cols[1]!, y)
    doc.text(money(line.commission).replace('GHS ', ''), cols[2]!, y)
    doc.text(money(line.deductions).replace('GHS ', ''), cols[3]!, y)
    doc.text(money(line.netPay).replace('GHS ', ''), cols[4]!, y)
    doc.text(line.status, cols[5]!, y)
    y += 6
  }

  doc.save(`payroll-summary-${input.run.periodStart ?? input.run.id}.pdf`)
}
